name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: echo "Hello, world!"
      - name: Show current time
        run: date
      - name: Show directory content
        run: ls -l
